In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.DataFrame({ 'Gender':['Male','Female','Female','Male','Female','Female','Male'],
               'Education':['Graduate','College','Graduate','High School','College','Graduate','High School']})
df

   Gender    Education
0    Male     Graduate
1  Female      College
2  Female     Graduate
3    Male  High School
4  Female      College
5  Female     Graduate
6    Male  High School

In [3]:
x = df[['Gender']]
y = df['Education']

In [4]:
OHE = OneHotEncoder()
converted = OHE.fit_transform(df)
value = converted.toarray()
cat_name = OHE.get_feature_names_out()
cat_name

array(['Gender_Female', 'Gender_Male', 'Education_College',
       'Education_Graduate', 'Education_High School'], dtype=object)

In [5]:
Output = pd.DataFrame(value,columns=cat_name)
Output

,Gender_Female,Gender_Male,Education_College,Education_Graduate,Education_High School
0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,1.0,0.0,0.0
5,1.0,0.0,0.0,1.0,0.0
6,0.0,1.0,0.0,0.0,1.0