In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.4.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print(f"Path of dataset files : {path}")

Using Colab cache for faster access to the 'insurance' dataset.
Path of dataset files : /kaggle/input/insurance

In [3]:
import os
print(os.getcwd())

/content

In [4]:
import pandas as pd

In [6]:
os.listdir(path)

['insurance.csv']

In [7]:
df = pd.read_csv(os.path.join(path, 'insurance.csv'))

In [8]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [10]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [12]:
# Split dataset before encoding
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [13]:
# Encode cetagorical variable
label_encoder = {}
for col in ['sex', 'smoker', 'region']:
  le = LabelEncoder()
  train_df[col] = le.fit_transform(train_df[col])
  test_df[col] = le.transform(test_df[col])
  label_encoder[col] = le

In [14]:
# Features and target
X_train = train_df.drop(columns=['charges'])
y_train = train_df['charges']

X_test = test_df.drop(columns=['charges'])
y_test = test_df['charges']

In [15]:
print(X_train.head())
print(y_train.head())

      age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1
560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
Name: charges, dtype: float64

In [16]:
# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]

In [18]:
# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [19]:
print(y_train_tensor)
print(y_train_tensor.shape)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])
torch.Size([1070, 1])

In [20]:
print(X_test_tensor)
print(X_test_tensor.shape)

tensor([[ 0.4011, -1.0246, -0.8915,  0.7343, -0.5087, -1.3533],
        [-0.2386, -1.0246, -0.0895, -0.9112, -0.5087, -0.4561],
        [ 1.7518, -1.0246, -0.6085, -0.9112,  1.9656, -0.4561],
        ...,
        [-0.0965,  0.9760, -0.4197, -0.0884, -0.5087, -1.3533],
        [ 1.0409, -1.0246,  2.7894, -0.9112,  1.9656,  0.4410],
        [ 0.8277, -1.0246,  0.6025, -0.0884, -0.5087,  1.3382]])
torch.Size([268, 6])

In [21]:
# Define Neural network model

class SimpleNNRegressionModel(nn.Module):
  def __init__(self, input_dim):
    super(SimpleNNRegressionModel, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 64),
        nn.ReLU(),
        nn.Linear(64, 128),
        nn.ReLU(),
        nn.Linear(128, 1)
    )

  def forward(self, x):
    return self.network(x)

In [22]:
X_train_tensor.shape

torch.Size([1070, 6])

In [23]:
input_dim = X_train_tensor.shape[1]
model = SimpleNNRegressionModel(input_dim)

In [24]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [25]:
# Loss and optmiser

criterion = nn.MSELoss()
optimiser = optim.Adam(model.parameters(), lr=0.01)

In [26]:
# Training loop
epochs = 30000

for epoch in range(epochs):
  model.train()
  optimiser.zero_grad()
  predictions = model(X_train_tensor)
  loss = criterion(predictions, y_train_tensor)
  loss.backward()

  optimiser.step()

  if (epoch+1) % 100 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss : {loss.item():.4f}")

Epoch [100/30000], Loss : 48558500.0000
Epoch [200/30000], Loss : 31636042.0000
Epoch [300/30000], Loss : 28793622.0000
Epoch [400/30000], Loss : 27017682.0000
Epoch [500/30000], Loss : 26069584.0000
Epoch [600/30000], Loss : 25378632.0000
Epoch [700/30000], Loss : 24785224.0000
Epoch [800/30000], Loss : 24327868.0000
Epoch [900/30000], Loss : 23961672.0000
Epoch [1000/30000], Loss : 23655342.0000
Epoch [1100/30000], Loss : 23397660.0000
Epoch [1200/30000], Loss : 23136040.0000
Epoch [1300/30000], Loss : 22933348.0000
Epoch [1400/30000], Loss : 22774034.0000
Epoch [1500/30000], Loss : 22633978.0000
Epoch [1600/30000], Loss : 22512746.0000
Epoch [1700/30000], Loss : 22385202.0000
Epoch [1800/30000], Loss : 22253714.0000
Epoch [1900/30000], Loss : 22121204.0000
Epoch [2000/30000], Loss : 21979822.0000
Epoch [2100/30000], Loss : 21825958.0000
Epoch [2200/30000], Loss : 21625846.0000
Epoch [2300/30000], Loss : 21293274.0000
Epoch [2400/30000], Loss : 20711422.0000
Epoch [2500/30000], Loss : 19987212.0000
Epoch [2600/30000], Loss : 19193556.0000
Epoch [2700/30000], Loss : 18505624.0000
Epoch [2800/30000], Loss : 17950758.0000
Epoch [2900/30000], Loss : 17414102.0000
Epoch [3000/30000], Loss : 16963626.0000
Epoch [3100/30000], Loss : 16534247.0000
Epoch [3200/30000], Loss : 16191827.0000
Epoch [3300/30000], Loss : 15869315.0000
Epoch [3400/30000], Loss : 15628704.0000
Epoch [3500/30000], Loss : 15354434.0000
Epoch [3600/30000], Loss : 15148688.0000
Epoch [3700/30000], Loss : 14999982.0000
Epoch [3800/30000], Loss : 14845067.0000
Epoch [3900/30000], Loss : 14672225.0000
Epoch [4000/30000], Loss : 14542226.0000
Epoch [4100/30000], Loss : 14399791.0000
Epoch [4200/30000], Loss : 14286272.0000
Epoch [4300/30000], Loss : 14144090.0000
Epoch [4400/30000], Loss : 14006998.0000
Epoch [4500/30000], Loss : 13895581.0000
Epoch [4600/30000], Loss : 13701014.0000
Epoch [4700/30000], Loss : 13479644.0000
Epoch [4800/30000], Loss : 13262471.0000
Epoch [4900/30000], Loss : 13093283.0000
Epoch [5000/30000], Loss : 12944593.0000
Epoch [5100/30000], Loss : 12804011.0000
Epoch [5200/30000], Loss : 12672754.0000
Epoch [5300/30000], Loss : 12552208.0000
Epoch [5400/30000], Loss : 12445348.0000
Epoch [5500/30000], Loss : 12333439.0000
Epoch [5600/30000], Loss : 12223099.0000
Epoch [5700/30000], Loss : 12100563.0000
Epoch [5800/30000], Loss : 12008260.0000
Epoch [5900/30000], Loss : 11932488.0000
Epoch [6000/30000], Loss : 11865377.0000
Epoch [6100/30000], Loss : 11761914.0000
Epoch [6200/30000], Loss : 11685703.0000
Epoch [6300/30000], Loss : 11621327.0000
Epoch [6400/30000], Loss : 11550573.0000
Epoch [6500/30000], Loss : 11478320.0000
Epoch [6600/30000], Loss : 11400092.0000
Epoch [6700/30000], Loss : 11317468.0000
Epoch [6800/30000], Loss : 11231489.0000
Epoch [6900/30000], Loss : 11141211.0000
Epoch [7000/30000], Loss : 11059499.0000
Epoch [7100/30000], Loss : 10990561.0000
Epoch [7200/30000], Loss : 10919297.0000
Epoch [7300/30000], Loss : 10842012.0000
Epoch [7400/30000], Loss : 10788770.0000
Epoch [7500/30000], Loss : 10731854.0000
Epoch [7600/30000], Loss : 10686668.0000
Epoch [7700/30000], Loss : 10638534.0000
Epoch [7800/30000], Loss : 10585433.0000
Epoch [7900/30000], Loss : 10513091.0000
Epoch [8000/30000], Loss : 10435131.0000
Epoch [8100/30000], Loss : 10390062.0000
Epoch [8200/30000], Loss : 10341439.0000
Epoch [8300/30000], Loss : 10285654.0000
Epoch [8400/30000], Loss : 10241331.0000
Epoch [8500/30000], Loss : 10192102.0000
Epoch [8600/30000], Loss : 10150671.0000
Epoch [8700/30000], Loss : 10106566.0000
Epoch [8800/30000], Loss : 10064320.0000
Epoch [8900/30000], Loss : 10021062.0000
Epoch [9000/30000], Loss : 9983157.0000
Epoch [9100/30000], Loss : 9945233.0000
Epoch [9200/30000], Loss : 9908389.0000
Epoch [9300/30000], Loss : 9879171.0000
Epoch [9400/30000], Loss : 9828700.0000
Epoch [9500/30000], Loss : 9786010.0000
Epoch [9600/30000], Loss : 9756272.0000
Epoch [9700/30000], Loss : 9731135.0000
Epoch [9800/30000], Loss : 9697838.0000
Epoch [9900/30000], Loss : 9646406.0000
Epoch [10000/30000], Loss : 9595889.0000
Epoch [10100/30000], Loss : 9540535.0000
Epoch [10200/30000], Loss : 9482866.0000
Epoch [10300/30000], Loss : 9432116.0000
Epoch [10400/30000], Loss : 9407570.0000
Epoch [10500/30000], Loss : 9351835.0000
Epoch [10600/30000], Loss : 9329420.0000
Epoch [10700/30000], Loss : 9269494.0000
Epoch [10800/30000], Loss : 9234379.0000
Epoch [10900/30000], Loss : 9194201.0000
Epoch [11000/30000], Loss : 9182584.0000
Epoch [11100/30000], Loss : 9137542.0000
Epoch [11200/30000], Loss : 9105202.0000
Epoch [11300/30000], Loss : 9093464.0000
Epoch [11400/30000], Loss : 9067461.0000
Epoch [11500/30000], Loss : 9038667.0000
Epoch [11600/30000], Loss : 9023218.0000
Epoch [11700/30000], Loss : 8992233.0000
Epoch [11800/30000], Loss : 8959222.0000
Epoch [11900/30000], Loss : 8932859.0000
Epoch [12000/30000], Loss : 8917929.0000
Epoch [12100/30000], Loss : 8892489.0000
Epoch [12200/30000], Loss : 8862147.0000
Epoch [12300/30000], Loss : 8822477.0000
Epoch [12400/30000], Loss : 8793577.0000
Epoch [12500/30000], Loss : 8769780.0000
Epoch [12600/30000], Loss : 8748906.0000
Epoch [12700/30000], Loss : 8718325.0000
Epoch [12800/30000], Loss : 8697293.0000
Epoch [12900/30000], Loss : 8671466.0000
Epoch [13000/30000], Loss : 8657479.0000
Epoch [13100/30000], Loss : 8633155.0000
Epoch [13200/30000], Loss : 8611517.0000
Epoch [13300/30000], Loss : 8601536.0000
Epoch [13400/30000], Loss : 8556619.0000
Epoch [13500/30000], Loss : 8542168.0000
Epoch [13600/30000], Loss : 8535937.0000
Epoch [13700/30000], Loss : 8515546.0000
Epoch [13800/30000], Loss : 8486865.0000
Epoch [13900/30000], Loss : 8492635.0000
Epoch [14000/30000], Loss : 8470407.0000
Epoch [14100/30000], Loss : 8451413.0000
Epoch [14200/30000], Loss : 8441600.0000
Epoch [14300/30000], Loss : 8427846.0000
Epoch [14400/30000], Loss : 8393669.0000
Epoch [14500/30000], Loss : 8366213.0000
Epoch [14600/30000], Loss : 8383679.5000
Epoch [14700/30000], Loss : 8342154.0000
Epoch [14800/30000], Loss : 8332266.0000
Epoch [14900/30000], Loss : 8317182.5000
Epoch [15000/30000], Loss : 8314095.5000
Epoch [15100/30000], Loss : 8292663.0000
Epoch [15200/30000], Loss : 8282856.5000
Epoch [15300/30000], Loss : 8286203.0000
Epoch [15400/30000], Loss : 8260190.0000
Epoch [15500/30000], Loss : 8265341.5000
Epoch [15600/30000], Loss : 8232930.5000
Epoch [15700/30000], Loss : 8234591.5000
Epoch [15800/30000], Loss : 8206256.5000
Epoch [15900/30000], Loss : 8196924.0000
Epoch [16000/30000], Loss : 8203008.5000
Epoch [16100/30000], Loss : 8198730.5000
Epoch [16200/30000], Loss : 8149922.0000
Epoch [16300/30000], Loss : 8145156.5000
Epoch [16400/30000], Loss : 8120028.0000
Epoch [16500/30000], Loss : 8108080.0000
Epoch [16600/30000], Loss : 8097419.5000
Epoch [16700/30000], Loss : 8087988.5000
Epoch [16800/30000], Loss : 8071724.0000
Epoch [16900/30000], Loss : 8056044.5000
Epoch [17000/30000], Loss : 8046443.5000
Epoch [17100/30000], Loss : 8041262.5000
Epoch [17200/30000], Loss : 8023315.5000
Epoch [17300/30000], Loss : 8018901.5000
Epoch [17400/30000], Loss : 7999211.0000
Epoch [17500/30000], Loss : 8007626.0000
Epoch [17600/30000], Loss : 7989505.5000
Epoch [17700/30000], Loss : 7979708.5000
Epoch [17800/30000], Loss : 7971635.5000
Epoch [17900/30000], Loss : 7954774.5000
Epoch [18000/30000], Loss : 7941339.0000
Epoch [18100/30000], Loss : 7925198.5000
Epoch [18200/30000], Loss : 7925356.0000
Epoch [18300/30000], Loss : 7939693.5000
Epoch [18400/30000], Loss : 7899352.5000
Epoch [18500/30000], Loss : 7887262.0000
Epoch [18600/30000], Loss : 7890136.5000
Epoch [18700/30000], Loss : 7879280.0000
Epoch [18800/30000], Loss : 7847515.0000
Epoch [18900/30000], Loss : 7849859.0000
Epoch [19000/30000], Loss : 7819073.0000
Epoch [19100/30000], Loss : 7824349.0000
Epoch [19200/30000], Loss : 7796077.5000
Epoch [19300/30000], Loss : 7785163.5000
Epoch [19400/30000], Loss : 7777880.0000
Epoch [19500/30000], Loss : 7765542.5000
Epoch [19600/30000], Loss : 7771719.0000
Epoch [19700/30000], Loss : 7751855.0000
Epoch [19800/30000], Loss : 7741842.5000
Epoch [19900/30000], Loss : 7736695.5000
Epoch [20000/30000], Loss : 7749301.5000
Epoch [20100/30000], Loss : 7719466.0000
Epoch [20200/30000], Loss : 7701406.5000
Epoch [20300/30000], Loss : 7687043.0000
Epoch [20400/30000], Loss : 7680279.5000
Epoch [20500/30000], Loss : 7674337.5000
Epoch [20600/30000], Loss : 7657398.5000
Epoch [20700/30000], Loss : 7659219.0000
Epoch [20800/30000], Loss : 7635360.0000
Epoch [20900/30000], Loss : 7626141.0000
Epoch [21000/30000], Loss : 7639681.0000
Epoch [21100/30000], Loss : 7614458.0000
Epoch [21200/30000], Loss : 7612822.0000
Epoch [21300/30000], Loss : 7635657.0000
Epoch [21400/30000], Loss : 7591687.0000
Epoch [21500/30000], Loss : 7577125.5000
Epoch [21600/30000], Loss : 7556100.0000
Epoch [21700/30000], Loss : 7547865.5000
Epoch [21800/30000], Loss : 7536683.5000
Epoch [21900/30000], Loss : 7524640.0000
Epoch [22000/30000], Loss : 7536314.5000
Epoch [22100/30000], Loss : 7507649.5000
Epoch [22200/30000], Loss : 7504440.0000
Epoch [22300/30000], Loss : 7497804.5000
Epoch [22400/30000], Loss : 7480448.0000
Epoch [22500/30000], Loss : 7485151.0000
Epoch [22600/30000], Loss : 7456456.0000
Epoch [22700/30000], Loss : 7451214.5000
Epoch [22800/30000], Loss : 7447977.0000
Epoch [22900/30000], Loss : 7444251.5000
Epoch [23000/30000], Loss : 7429893.0000
Epoch [23100/30000], Loss : 7423600.5000
Epoch [23200/30000], Loss : 7407359.5000
Epoch [23300/30000], Loss : 7413759.0000
Epoch [23400/30000], Loss : 7396418.5000
Epoch [23500/30000], Loss : 7388733.0000
Epoch [23600/30000], Loss : 7396027.0000
Epoch [23700/30000], Loss : 7392346.0000
Epoch [23800/30000], Loss : 7351840.5000
Epoch [23900/30000], Loss : 7314573.5000
Epoch [24000/30000], Loss : 7290360.5000
Epoch [24100/30000], Loss : 7288750.5000
Epoch [24200/30000], Loss : 7263694.5000
Epoch [24300/30000], Loss : 7248153.5000
Epoch [24400/30000], Loss : 7238482.0000
Epoch [24500/30000], Loss : 7229697.5000
Epoch [24600/30000], Loss : 7206453.5000
Epoch [24700/30000], Loss : 7200406.5000
Epoch [24800/30000], Loss : 7175451.0000
Epoch [24900/30000], Loss : 7170228.0000
Epoch [25000/30000], Loss : 7176696.5000
Epoch [25100/30000], Loss : 7158968.0000
Epoch [25200/30000], Loss : 7152280.5000
Epoch [25300/30000], Loss : 7138382.5000
Epoch [25400/30000], Loss : 7129036.5000
Epoch [25500/30000], Loss : 7143241.5000
Epoch [25600/30000], Loss : 7118798.0000
Epoch [25700/30000], Loss : 7108290.5000
Epoch [25800/30000], Loss : 7142825.0000
Epoch [25900/30000], Loss : 7111264.0000
Epoch [26000/30000], Loss : 7101480.5000
Epoch [26100/30000], Loss : 7084321.5000
Epoch [26200/30000], Loss : 7080358.0000
Epoch [26300/30000], Loss : 7096655.0000
Epoch [26400/30000], Loss : 7078611.5000
Epoch [26500/30000], Loss : 7062677.5000
Epoch [26600/30000], Loss : 7074005.0000
Epoch [26700/30000], Loss : 7055807.5000
Epoch [26800/30000], Loss : 7059920.0000
Epoch [26900/30000], Loss : 7037181.0000
Epoch [27000/30000], Loss : 7045824.5000
Epoch [27100/30000], Loss : 7030388.5000
Epoch [27200/30000], Loss : 7031320.0000
Epoch [27300/30000], Loss : 7010439.0000
Epoch [27400/30000], Loss : 7016550.0000
Epoch [27500/30000], Loss : 6999244.0000
Epoch [27600/30000], Loss : 7007727.0000
Epoch [27700/30000], Loss : 6981683.5000
Epoch [27800/30000], Loss : 6981790.0000
Epoch [27900/30000], Loss : 6965976.5000
Epoch [28000/30000], Loss : 6964503.0000
Epoch [28100/30000], Loss : 6960805.0000
Epoch [28200/30000], Loss : 6961932.0000
Epoch [28300/30000], Loss : 6951952.5000
Epoch [28400/30000], Loss : 6939605.5000
Epoch [28500/30000], Loss : 6937049.0000
Epoch [28600/30000], Loss : 6951699.0000
Epoch [28700/30000], Loss : 6943608.5000
Epoch [28800/30000], Loss : 6922357.5000
Epoch [28900/30000], Loss : 6911448.5000
Epoch [29000/30000], Loss : 6916491.0000
Epoch [29100/30000], Loss : 6901874.0000
Epoch [29200/30000], Loss : 6930580.0000
Epoch [29300/30000], Loss : 6905127.0000
Epoch [29400/30000], Loss : 6890660.5000
Epoch [29500/30000], Loss : 6882451.5000
Epoch [29600/30000], Loss : 6880856.0000
Epoch [29700/30000], Loss : 6884558.0000
Epoch [29800/30000], Loss : 6874504.5000
Epoch [29900/30000], Loss : 6865168.0000
Epoch [30000/30000], Loss : 6874501.5000

In [27]:
# Model Evaluation

model.eval()
y_pred = model(X_test_tensor).detach().numpy()

In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_test_numpy = y_test_tensor.numpy()

# Calculate metrics
mse = mean_squared_error(y_test_numpy, y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test_numpy, y_pred)
r2 = r2_score(y_test_numpy, y_pred)

print(f"MSE : {mse}")
print(f"RMSE : {rmse}")
print(f"MAE : {mae}")
print(f"R2-Score : {r2}")

# 0 --> 0

MSE : 44534760.0
RMSE : 6673.436895633314
MAE : 4534.7822265625
R2-Score : 0.7131392955780029

In [29]:
def predict_charges(age, sex, bmi, children, smoker,region):
  input_data = pd.DataFrame([[age, sex, bmi, children, smoker,region]],
               columns=['age', 'sex', 'bmi', 'children', 'smoker', 'region'])

  for col in ['sex', 'smoker', 'region']:
    input_data[col] = label_encoder[col].transform(input_data[col])
  input_data = scaler.transform(input_data)
  input_tensor = torch.tensor(input_data, dtype=torch.float32)
  predicted_charge = model(input_tensor).item()
  return predicted_charge

In [30]:
predicted = predict_charges(50, 'female', 27.9, 0, 'yes', 'southwest')

In [31]:
print(f"Predicted insurance charge: ${predicted:.2f}")

Predicted insurance charge: $24344.98